### ISSUE TITLE
Создать проект с классами и методами заглушками

### ISSUE THREAD

**Issue by ni032mas** [khasang/Poti#5]
Создать проект со всеми классами, переменными и методами заглушками описанными в архитектуре. Ресурсы делать не надо. Ориентировочное время выполнения 3 часа. Выполняется в первую очередь. Пока данная задача не будет выполнена к другим нельзя приступать.

**Comment by SpaceProg** [comment]
Взяла эту задачу, сделаю до 27.10.2015
